const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Exps.XAt,
		C3.Plugins.Touch.Exps.YAt,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Exps.TouchCount,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Touch.Cnds.OnDoubleTapGesture
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Browser: 0},
	{FondoEscena1: 0},
	{Rudolph_Escena1: 0},
	{initialX: 0},
	{initialY: 0},
	{GenteCaminando_Escena1: 0},
	{FondoEscuela_Escena1: 0},
	{Fondo_Escena2: 0},
	{TestingText: 0},
	{FondoMenu: 0},
	{RudolphMenu: 0},
	{SF_Juego: 0},
	{zoomProgress: 0},
	{isPinching: 0},
	{pinchStartDistance: 0},
	{pinchMaxDistance: 0},
	{pinchPreviewAdd: 0},
	{PINCH_TO_FULL: 0},
	{MAX_ADD_PER_PINCH: 0},
	{GENTE_Y_PASS: 0},
	{delta: 0},
	{currentDistance: 0},
	{sceneProgress: 0},
	{isDragging: 0},
	{dragStartX: 0},
	{dragStartY: 0},
	{cameraStartX: 0},
	{cameraStartY: 0},
	{deltaX: 0},
	{deltaY: 0},
	{targetX: 0},
	{targetY: 0},
	{minX: 0},
	{minY: 0},
	{maxX: 0},
	{maxY: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	FondoEscena1: class extends self.ISpriteInstance {},
	Rudolph_Escena1: class extends self.ISpriteInstance {},
	GenteCaminando_Escena1: class extends self.ISpriteInstance {},
	FondoEscuela_Escena1: class extends self.ISpriteInstance {},
	Fondo_Escena2: class extends self.ISpriteInstance {},
	TestingText: class extends self.ITextInstance {},
	FondoMenu: class extends self.ISpriteInstance {},
	RudolphMenu: class extends self.ISpriteInstance {},
	SF_Juego: class extends self.ITextInstance {}
}