const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Behaviors.Timer,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Exps.XAt,
		C3.Plugins.Touch.Exps.YAt,
		C3.Plugins.Browser.Acts.Vibrate,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.System.Exps.max,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Exps.TouchCount,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Behaviors.Tween.Acts.PauseAllTweens,
		C3.Behaviors.Tween.Acts.ResumeAllTweens,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.TiledBg.Exps.Opacity,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Cnds.CompareOpacity,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.Audio.Acts.Stop
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Browser: 0},
	{Audio: 0},
	{FondoEscena1: 0},
	{initialY: 0},
	{walkPhase: 0},
	{minX: 0},
	{maxX: 0},
	{currentRoute: 0},
	{Sine: 0},
	{DragDrop: 0},
	{Rudolph_Escena1: 0},
	{FinalWith: 0},
	{FinalHeight: 0},
	{Final_X: 0},
	{Final_Y: 0},
	{TimeToDoor: 0},
	{initialX: 0},
	{GenteCaminando_Escena1: 0},
	{FondoEscuela_Escena1: 0},
	{GenteCaminando2_Escena1: 0},
	{Fondo_Escena2: 0},
	{Rudolph_Escena2: 0},
	{index: 0},
	{clicksCount: 0},
	{ElementoPatioEscuela1: 0},
	{ElementoPatioEscuela2: 0},
	{ElementoPatioEscuela3: 0},
	{ElementoPatioEscuela4: 0},
	{FondoEscena3: 0},
	{approachProgress: 0},
	{currentScale: 0},
	{MinScale: 0},
	{MaxScale: 0},
	{Escena3_PuntoFinal: 0},
	{type: 0},
	{Escena3_Ninia1: 0},
	{Escena3_Ninia2: 0},
	{Escena3_Ninia3: 0},
	{Escena3_Ninia4: 0},
	{Senio_Escena3: 0},
	{Tween: 0},
	{Fondo2_Escena3: 0},
	{CieloEscena3: 0},
	{TestingText: 0},
	{FondoMenu: 0},
	{RudolphMenu: 0},
	{SF_Juego: 0},
	{FadeObject_Back: 0},
	{FadeObject_White: 0},
	{Tutorial_Zoom: 0},
	{Elementos_Escena2: 0},
	{PersonasEscena3: 0},
	{Timer: 0},
	{Tutoriales: 0},
	{GenteEscena_1: 0},
	{zoomProgress: 0},
	{isPinching: 0},
	{pinchStartDistance: 0},
	{pinchMaxDistance: 0},
	{pinchPreviewAdd: 0},
	{PINCH_TO_FULL: 0},
	{MAX_ADD_PER_PINCH: 0},
	{GENTE_Y_PASS: 0},
	{delta: 0},
	{currentDistance: 0},
	{sceneProgress: 0},
	{GameState: 0},
	{isDragging: 0},
	{dragStartX: 0},
	{dragStartY: 0},
	{cameraStartX: 0},
	{cameraStartY: 0},
	{Esc2_currentElement: 0},
	{movingToNextElement: 0},
	{cantidadDeElementos: 0},
	{SPAWN_Y: 0},
	{TARGET_Y: 0},
	{VelocidadNinios: 0},
	{CantidadDeNiniosEscena3: 0},
	{Scale_TopeDeLaLoma: 0},
	{Tiempo_HastaLoma: 0},
	{Tiempo_HastaFinal: 0},
	{PersonaUID: 0},
	{FadeSpeed: 0},
	{proximaAccion: 0},
	{tiempoDeTutorial: 0},
	{musicFading: 0},
	{randomMusic: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	FondoEscena1: class extends self.ISpriteInstance {},
	Rudolph_Escena1: class extends self.ISpriteInstance {},
	GenteCaminando_Escena1: class extends self.ISpriteInstance {},
	FondoEscuela_Escena1: class extends self.ISpriteInstance {},
	GenteCaminando2_Escena1: class extends self.ISpriteInstance {},
	Fondo_Escena2: class extends self.ISpriteInstance {},
	Rudolph_Escena2: class extends self.ISpriteInstance {},
	ElementoPatioEscuela1: class extends self.ISpriteInstance {},
	ElementoPatioEscuela2: class extends self.ISpriteInstance {},
	ElementoPatioEscuela3: class extends self.ISpriteInstance {},
	ElementoPatioEscuela4: class extends self.ISpriteInstance {},
	FondoEscena3: class extends self.ISpriteInstance {},
	Escena3_Ninia1: class extends self.ISpriteInstance {},
	Escena3_Ninia2: class extends self.ISpriteInstance {},
	Escena3_Ninia3: class extends self.ISpriteInstance {},
	Escena3_Ninia4: class extends self.ISpriteInstance {},
	Senio_Escena3: class extends self.ISpriteInstance {},
	Fondo2_Escena3: class extends self.ISpriteInstance {},
	CieloEscena3: class extends self.ISpriteInstance {},
	TestingText: class extends self.ITextInstance {},
	FondoMenu: class extends self.ISpriteInstance {},
	RudolphMenu: class extends self.ISpriteInstance {},
	SF_Juego: class extends self.ITextInstance {},
	FadeObject_Back: class extends self.ITiledBackgroundInstance {},
	FadeObject_White: class extends self.ITiledBackgroundInstance {},
	Tutorial_Zoom: class extends self.ISpriteInstance {},
	Elementos_Escena2: class extends self.ISpriteInstance {},
	PersonasEscena3: class extends self.ISpriteInstance {},
	Tutoriales: class extends self.ISpriteInstance {},
	GenteEscena_1: class extends self.ISpriteInstance {}
}